### PR TITLE
Add transient caching to REST api calls triggered on frontend

### PR DESCRIPTION
**Pull request by oxyc**
Currently there are several REST api calls triggered on the frontend each time a form is rendered.

This is a quick fix that uses transient caching to avoid calling these more than once per day from the frontend but I haven't really looked at when the data is used so might not get invalidated when it needs to.

Consider this a bug report :)

### CODE REVIEW

**Comment by oxyc** [comment]
Would be nice to get this fixed since we cannot use your plugin. Your remote API request takes longer than rendering the rest of the page.

**Comment by oxyc** [comment]
Rebasing. Noting that this PR is still just a quick fix to allow us to use your plugin

Would be nice if you fixed this since your remote API request _on every page request_ is an ridiculous performance hit on page rendering. Using lianamailer more than doubles the rendering time of every page which has a form now.

**Comment by oxyc** [comment]
Ping @LianaTechnologies @lianatech-sami-siuvatti  since you guys might not be reading this. Both me and @RodCyb3Dev in the other PR are trying to help you fix your issues but 2 years without response is already unacceptable.

**Comment by lianatech-sami-siuvatti** [comment]
@oxyc hello! You're right, my sincere apologies and thank you for contributing!

I was recently assigned to handle these plugins and the related project(s) and this PR has not been in my radar so far, but I'll look into it today.

**Pull request merged**
